shop/urls.py
from django.conf.urls import url
from . import views

app_name = 'shop'

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name ='index'),
		# /shop/id/
		url(r'^(?P<pk>[0-9]+)$', views.DetailView.as_view(), name='detail')
]

tstore/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
		url(r'^shop/', include('shop.urls')),
    url(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/models.py
from django.db import models

# Create your models here.
class Shirt(models.Model):
	name = models.CharField(max_length=200)
	stock = models.IntegerField(default=70)
	image = models.FileField()
	price = models.IntegerField(default=7)
	desc = models.CharField(max_length=1000)
	
	def __str__(self):
		return self.name + ": " + str(self.stock)
	
	def out_of_stock(self):
		if self.stock == 0:
			return self.name

shop/views.py
from django.views import generic
from .models import Shirt

class IndexView(generic.ListView):
	template_name = 'shop/index.html'
	context_object_name = 'all_shirts' # so we don't have to use 'object_list' when calling the variable
	
	def get_queryset(self):
		return Shirt.objects.all()	
	
class DetailView(generic.DetailView):
	model = Shirt
	template_name = 'shop/detail.html'
	

shop/templates/shop/base.html
<!DOCTYPE html>
<html lang="en">
<head>
	{% load staticfiles %}
	<link rel="stylesheet" href="{% static 'shop/style.css' %}">
	<link href="https://fonts.googleapis.com/css?family=Fugaz+One|Noto+Sans|Roboto|Pontano+Sans" rel="stylesheet">
	<meta charset="UTF-8">
	<title>Welcome to Tstores, your #1 place for tShirts</title>
	
</head>
<body>
<nav>
	<div class="navHeader">
		<a href="{% url 'shop:index' %}">Tstore</a>
	</div>
	<div class="navItems">
		<ul class="navBarMain">
			<li><a href="#">Men</a></li>
			<li><a href="#">Women</a></li>
			<li><a href="#">Kids</a></li>
			
			<form action="#" class="navbarForm" role="search" method="get">
				<input type="text" class="formInput" name="" value="">
				<button type="submit" class="searchBtn">Search</button>
			</form>
		</ul>

	</div>
</nav>
	{% block body %}
	{% endblock %}
</body>
</html>

shop/templates/shop/detail.html
{% extends 'shop/base.html' %}

{% block body %}
<div id="container">
	<div class="detailLeft">
		<h2 class="shirtName">{{ shirt.name }}</h2>
		<br>
		<img class="detailImg" src="{{ shirt.image.url }}" alt="">
	</div>
	
	<div class="detailRight">
		<h2>£{{ shirt.price }}</h2>

		<span>{{ shirt.desc }}</span>
		<br>
		<button class="basketBtn" type="submit">Add to basket</button>
	</div>
	
</div>
{% endblock %}

shop/templates/shop/index.html
{% extends 'shop/base.html' %}

{% block body %}
	<h1>Browse our shirts</h1>
	{% if all_shirts %}
	<ul>
	{% for shirt in all_shirts %}
	<a href="{% url 'shop:detail' shirt.id %}">
		<div class="shirtIcon">
			<img class="iconImg" src="{{ shirt.image.url }}" alt="">
			<li class="shirtTitle"><a style="text-decoration:none" href="{% url 'shop:detail' shirt.id %}">{{ shirt.name }}</a></li>
			<p class="shirtPrice">£{{ shirt.price }}</p>
		</div>
	</a>
	{% endfor %}
	</ul>
	{% else %}
	<h1>No Shirts Available</h1>
	{% endif %}
{% endblock %}